"""Descripción de la migración

Revision ID: f6be9e9b5eff
Revises: 
Create Date: 2024-09-16 22:20:44.073752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6be9e9b5eff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lugar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_identidad', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('apellidos', sa.String(length=64), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('cantidad_mascotas', sa.Integer(), nullable=False),
    sa.Column('semana_inicio', sa.String(length=10), nullable=False),
    sa.Column('lugar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona')
    op.drop_table('lugar')
    # ### end Alembic commands ###
